steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - env_vars
      - redbubblesearchbot_http
      - --runtime=python37
      - --trigger-http
      - --set-env-vars PROJECT_NAME=torbjorn-zetterlund
      - --region=europe-west1
      - --memory=128MB
      - --timeout=240
    id: "deploying-a-serverless-function"
    dir: "gpi-techlab-redbubblesearchbot"