steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - aliexpressbot_http
      - --runtime=python37
      - --trigger-http
      - --region=europe-west1
      - --memory=128MB
      - --timeout=240
    id: "deploying-a-serverless-function"
    dir: "gpi-techlab-amazonsearchbot"